defaults: &defaults
  docker:
    - image: circleci/node:10.15.3
  working_directory: ~/repo

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - root-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - root-npm-{{ .Branch }}
            - root-npm-
      - run: npm ci
      - save_cache:
          key: root-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - /root/.npm
      - persist_to_workspace:
          root: .
          paths: .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run lint
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: public
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: sudo npm i -g --unsafe-perm now
      - run: ./tool/now.sh

  android-lint:
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}
      - run: cd android && ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}
      - run: cd android && ./gradlew lint test
      - store_artifacts:
          path: android/app/build/reports
          destination: reports

workflows:
  version: 2
  deploy:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - build:
          requires:
            - lint
      - deploy:
          requires:
            - build
  android:
    jobs:
      - android-lint
